from setuptools import setup

setup(
    name='fchart3',
    version='0.4',
    description='Collection of Python scripts to make beautiful deepsky finder charts in various formats',
    keywords='fchart3 starchart star charts finder chart astronomy map',
    url='https://github.com/skybber/fchart3',
    author='Michiel Brentjens <brentjens@astron.nl>, Austin Riba <root@austinriba.com>, Vladimir Dvorak<lada.dvorak7@gmail.com',
    author_email='root@austinriba.com, lada.dvorak7@gmail.com',
    license='GPLv2',
    packages=['fchart3'],
    include_package_data=True,
    install_requires=['numpy'],
    scripts=['bin/fchart3', 'bin/tyc2_to_binary'],
    package_data={'fchart3': ['data/catalogs/index.dat',
                'data/catalogs/revngc.txt',
                'data/catalogs/revic.txt',
                'data/catalogs/sac.txt',
                'data/catalogs/vic.txt',
                'data/catalogs/bsc5.dat',
                'data/catalogs/ConstellationLines.dat',
                'data/catalogs/tyc2.bin',
                'data/label_positions.txt']},
)
